### PR TITLE
Add automatic download for CPS files

### PR DESCRIPTION
**Pull request by jdebacker**
This PR added and automatic download for the March CPS file.

@andersonfrailey I will also add a download for the `cps_raw.csv.gz`, but I don't know anything about the provenance of this file.

### CODE REVIEW

**Comment by jdebacker** [comment]
@andersonfrailey pinging - let me know how this looks.

**Comment by andersonfrailey** [comment]
This looks great, @jdebacker! Thanks for working on it. Seems ready to merge from my perspective. Are there any final changes you want to make before I merge?

**Comment by jdebacker** [comment]
@andersonfrailey Thanks for taking a look.  Yes, I'd like to add a download of the `cps_raw.csv.gz`.  Where exactly is that from?

**Comment by andersonfrailey** [comment]
@jdebacker there's nowhere to download that file. It gets created as you're running the CPS scripts and we've left it out of the repo to keep the size down.

**Comment by jdebacker** [comment]
@andersonfrailey Got it.  Ok - then this PR is ready to merge.

**Pull request merged**
