### PR TITLE
Documentation for CPS/PUF matching file [Review]

### PR DESCRIPTION
**Pull request by chusloj**
This PR creates `MATCH.md`, which is documentation for `cps-matched-puf.csv`, the statistical match file made between the CPS and PUF data files.

This document is still in progress and needs suggestions on what is missing/what should be included. Should this document have as much detail as [The CPS tax unit documentation](https://github.com/PSLmodels/taxdata/blob/master/cps_data/cps_file_doc.md)?

@MattHJensen

### CODE REVIEW

**Comment by MaxGhenis** [comment]
May be a good PR to also change `SAS` to `Python` in https://github.com/PSLmodels/taxdata/blob/master/puf_data/README.md

**Comment by chusloj** [comment]
> May be a good PR to also change `SAS` to `Python` in https://github.com/PSLmodels/taxdata/blob/master/puf_data/README.md

Thanks for bringing this up, I'll address this in my upcoming solver update for the `PUF` `stage2.py` file.

**Comment by andersonfrailey** [comment]
Sorry I let this sit for so long, @chusloj. Looks good to me. I'll merge after you resolve the conflicts.

**Comment by chusloj** [comment]
@andersonfrailey Merge conflicts addressed.

**Pull request merged**
