### PR TITLE
Update to CBO January 2020 economic projections and extend data to 2030

### PR DESCRIPTION
**Pull request by Peter-Metz**
This PR updates TaxData to use the latest CBO economic projections. The general steps I took were:

1. Follow instructions in [CBO_Baseline_Updating_Instructions.md](https://github.com/PSLmodels/taxdata/blob/master/puf_stage1/doc/CBO_Baseline_Updating_Instructions.md)
2. Run `puf_data/StatMatch/runmatch.py` after adding `asec2016_pubuse_v3.dat` to the repo
3. Run `Make all`

A few notes:
1. The format of the CBO capital gains [data](https://www.cbo.gov/system/files/2020-01/51138-2020-01-revenue-projections.xlsx) changed, so `updatecbo.py` does not successfully retrieve the CG data. I got around this by manually updating the CG data in `CBO_baseline.csv`, but we might want to address this issue in a future PR.
2. In running `Make all`, the new weights files did not successfully overwrite the old files. To get this process to work, I had to delete `*_weights.csv.gz` before running `Make all`.
3. I made a slight adjustment to `puf_stage2/stage2.py` [line 68](https://github.com/Peter-Metz/taxdata/blob/70c69f86bb9179655e62b71441644ace8ff0ff42/puf_stage2/stage2.py#L68) so that `stage3.py` is able to read the file.
4. @andersonfrailey confirmed that the 2030 growth rates in `benefit_growth_rates.csv` should be the same as 2027-2029. If this continues to be the case for future years, we should consider adding a note to `CBO_Baseline_Updating_Instructions.md`

cc @MattHJensen @andersonfrailey

### CODE REVIEW

**Comment by Peter-Metz** [comment]
Following up on our conversation during yesterday's Tax-Calc call, here's how the CBO update will affect aggregate Tax-Calc statistics using both the PUF and CPS:

Screen Shot 2020-03-04 at 12 03 29 PM
Screen Shot 2020-03-04 at 11 59 40 AM
Screen Shot 2020-03-04 at 12 03 40 PM
Screen Shot 2020-03-04 at 11 59 52 AM

I believe the direction of these results makes sense because some factors in `growfactors.csv` like inflation and wage growth were adjusted downwards, but would appreciate a second pair of eyes on this.

@MattHJensen @andersonfrailey

**Comment by andersonfrailey** [comment]
Thanks for the PR, @Peter-Metz. At a (very) quick glance, this looks good. I can give it a more thorough review next week if there's no rush to merge it and get a new version of Tax-Calc out

**Comment by donboyd5** [comment]
The changes look truly de minimis to me, too. Moderately interesting that
the longer-run (2029) CPS differences are larger than the longer-run PUF
differences but there are a lot of years in between and a lot of
potentially plausible explanations and in any event the differences still
are small. Don

**Comment by Peter-Metz** [comment]
Thanks a lot for the review @andersonfrailey and @donboyd5.

Anderson - there's no rush to merge so a closer look whenever you get the chance would be great. Thanks!

**Comment by andersonfrailey** [comment]
All seems good to me!

**Comment by MattHJensen** [comment]
@Peter-Metz, thanks a great deal for the PR and @donboyd5 and @andersonfrailey for the reviews. The results look to be as expected to me as well. Merging.

**Pull request merged**
