### PR TITLE
Update to January 2019 CBO Economic Projections

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR updates TaxData to use the latest CBO economic projections. I slightly modified the make file and the PUF stage 2 scripts to deal with an issue with how the weights file was saved. In terms of changes in total tax liability, projections change less than 1% except for 2018 where we see a tax increase of about 2% for both the PUF and the CPS likely due to increased income for that year in the projections.

cc @martinholmer

### CODE REVIEW

**Comment by martinholmer** [comment]
@andersonfrailey,  Shouldn't the title of this PR be: **Update to January 2019 CBO Economic Projections**?

I'm going to review the substance of this PR today and see if I can replicate the file revisions on my computer.
So, I won't be able to report back until Tuesday at the earliest.

**Comment by andersonfrailey** [comment]
@martinholmer 
>@andersonfrailey, Shouldn't the title of this PR be: Update to January 2019 CBO Economic Projections?

Ah, yep. Typo.

>I'm going to review the substance of this PR today and see if I can replicate the file revisions on my computer.
So, I won't be able to report back until Tuesday at the earliest.

Sounds good.

**Comment by martinholmer** [comment]
@andersonfrailey,  I can't even get started reviewing PR#307 because `make all` doesn't work on the master branch.  Here is the problem I encountered:
```
iMac:taxdata mrh$ git branch
* master
iMac:taxdata mrh$ ./gitsync 
Already up to date.
Everything up-to-date
iMac:taxdata mrh$ make all
cd ./puf_data/StatMatch/Matching ; python runmatch.py
Reading CPS Data from .CSV
Reading PUF Data
Creating CPS Tax Units
100%|█████████████████████████████████████| 69484/69484 [57:52<00:00, 20.01it/s]
CPS Tax Units Created
Adjustment Complete
Start Phase One
Start Phase Two
100%|███████████████████████████████████████████| 23/23 [00:01<00:00, 11.01it/s]
Creating final file
cd puf_data ; python finalprep.py
cd puf_stage1 ; python stage1.py
Traceback (most recent call last):
  File "stage1.py", line 158, in <module>
    soi_estimates.index = historical_index
  File "/Users/mrh/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 5080, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/Users/mrh/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 638, in _set_axis
    self._data.set_axis(axis, labels)
  File "/Users/mrh/anaconda3/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 155, in set_axis
    'values have {new} elements'.format(old=old_len, new=new_len))
ValueError: Length mismatch: Expected axis has 7 elements, new values have 8 elements
make: *** [puf_stage1/Stage_I_factors.csv] Error 1
iMac:taxdata mrh$ 
```

**Comment by andersonfrailey** [comment]
@martinholmer I ran into the same error when working on this PR. It's due to the variable `SOI_YR` being defined as 2015 rather than 2014 in line 8 of `puf_stage1/stage1.py`. This was introduced in PR #298. I must've messed up the commits at some point and not fixed that before merging. But it is fixed in this PR.

**Comment by martinholmer** [comment]
@andersonfrailey, When I run `make all` on PR #307 I don't get the same results as in the PR.  That is, when I do `git status` it shows that the `puf_stage2/puf_weights.csv.gz` file is different on my computer.  So, this brings up the question of why PR #307 makes the following change in the `Makefile`:

screen shot 2019-03-05 at 8 05 31 am

**Comment by andersonfrailey** [comment]
@martinholmer I made that change because with the `to_csv()` method in pandas you can specify the compression you'd like, making that additional step unnecessary.

**Comment by martinholmer** [comment]
@andersonfrailey said in #307:
> I made that change because with the `to_csv()` method in pandas you can specify the compression you'd like, making that additional step unnecessary.

The additional step in the `Makefile` has nothing to do with the type of compression but rather has to do with suppressing the timestamp info in the gz file's header.

**Comment by andersonfrailey** [comment]
@martinholmer thanks for clarifying, I was not aware of that. I'll revert that and we can see if we get the same results then.

**Comment by andersonfrailey** [comment]
@martinholmer, latest commit comes after running make all with the line I previously removed added back in. I get this md5 for the PUF weights: 5b016810b91161313aeaa697b885b212

And this one for the CPS weights: 7fc6f39f0c4afa2a32e537d64dc429dc

**Comment by martinholmer** [comment]
@andersonfrailey said in PR #307:
> latest commit comes after running `make all` with the line I previously removed added back in.

But then why is there this difference in the `Makefile`?

screen shot 2019-03-06 at 11 20 47 am

After your change, is the leading space on that line a tab character or many spaces?

**Comment by andersonfrailey** [comment]
@martinholmer, it looks like mine is a tab. I'm assuming the default is a bunch of spaces so I'll convert to spaces so the difference goes away.

**Comment by martinholmer** [comment]
@andersonfrailey said:
>  I get this md5 for the PUF weights: 5b016810b91161313aeaa697b885b212
> And this one for the CPS weights: 7fc6f39f0c4afa2a32e537d64dc429dc

After the 760e275 commit, I get the same results using PR #307 as a local branch on my computer.

Given that #307 has been reviewed and we get the same results on two different computers, it seems as if #307 should be merged into the taxdata master branch.  Thanks for reacting quickly to the user suggestion at the PSL Meetup on Monday, February 25th.

**Pull request merged**
