### PR TITLE
Replace filer variable with data_source

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR resolves issue #288. It renames `filer` to `data_source` in `puf.csv` and removes `filer` from `cps.csv.gz` completely.

### CODE REVIEW

**Comment by martinholmer** [comment]
@andersonfrailey said in taxdata pull request #296:
> This PR resolves issue #288. It renames `filer` to `data_source` in `puf.csv` and removes filer from `cps.csv.gz` completely.

Perhaps I'm confused, but I thought the `filer` variable was meant to indicate whether or not the filing unit was required to file an income tax return, and thus, some CPS-derived units could have a value of 1 for `filer`.  Am I confused?  Are you saying that in the old `puf.csv` that `filer` equals one if and only if the unit was mainly derived from the SOI-PUF data set?  In other words, are you saying that the old `filer` variable in the `puf.csv` file was equal to zero if and only if the unit was derived from the CPS?

**Comment by andersonfrailey** [comment]
@martinholmer asked:
>In other words, are you saying that the old filer variable in the puf.csv file was equal to zero if and only if the unit was derived from the CPS?

Correct. Any CPS units that were flagged as having to file were used in the statistical match and would end up being part of a unit primarily derived from the PUF.

**Comment by martinholmer** [comment]
@andersonfrailey said in taxdata pull request #296:
>> In other words, are you saying that the old filer variable in the puf.csv file was equal to zero if and only if the unit was derived from the CPS?
>
> Correct. Any CPS units that were flagged as having to file were used in the statistical match and would end up being part of a unit primarily derived from the PUF.

Thanks for the clarification.  I'd like to see if I can replicate the results of #296 on my computer.
What's the bytesize and MD5 checksum for the new `puf.csv` file generated with #296?
Assuming I can get the same two data files, pull request #296 will be ready for merging.

**Comment by andersonfrailey** [comment]
@martinholmer 
MD5: 4aa15435c319bf5e4d3427faf52384c0
Bytesize: 56415704

**Comment by martinholmer** [comment]
@andersonfrailey described the `puf.csv` file generated by PR #296 as follows:
> MD5: 4aa15435c319bf5e4d3427faf52384c0
> Bytesize: 56415704

I can get the same `puf.csv` file on my computer and the new `cps.csv.gz` file is the same as the file included in this PR.  So, everything looks good to me.  I suggest you merge #296 today.  Then I'll prepare a Tax-Calculator pull request that incorporates these two new data input files.

**Comment by martinholmer** [comment]
@andersonfrailey,  What the time schedule on merging taxdata PR #296?

**Comment by andersonfrailey** [comment]
@martinholmer, I'll merge now and distribute the new PUF shortly.

**Pull request merged**
