### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by jdebacker**
This PR updates the `taxdata` documentation.  It organizes existing documents into a Jupyter Book format, creates actions to test and deploy these docs, and adds markdown files with the content of three methodological references (which can now be more easily updated to conform with the current methods).

### CODE REVIEW

**Comment by jdebacker** [comment]
FYI, in addition to the documentation updates, I change the environment to allow Python > 3.7 (`taxdata` runs fine on 3.8 for me) and I changes the GH Action that runs the unit tests to run on Python 3.7 (since using 3.6 for tests gave package conflicts when trying to create the environment).

**Comment by jdebacker** [comment]
This PR is ready for review.

**Comment by jdebacker** [comment]
@andersonfrailey if you create a `gh-pages` branch and commit an empty file to it with the name `.nojekyll`, I think the docs should deploy to pslmodels.github.io/taxdata.

**Comment by jdebacker** [comment]
@andersonfrailey pinging - let me know how this looks.

**Comment by andersonfrailey** [comment]
This is fantastic, @jdebacker, thanks! I can't really tell from reading the Jupyterbook docs, should I create the `gh-pages` branch before or after this PR is merged?

**Comment by jdebacker** [comment]
@andersonfrailey Why don't you create it first and commit the `.nojekyll` file to it. Then merge this PR.  Thanks!

**Comment by andersonfrailey** [comment]
I've created the new branch with the `.nojekyll` file. Merging this!

**Pull request merged**
