### PR TITLE
CBOUpdate2

### PR DESCRIPTION
**Pull request by lmm8ka**
updated CBO baseline values using CBO 10 year projections, updating from August 2016 projections to the August 2018 projections. Aug 2018 includes actual values for the period between Aug 2016-2018. Also includes Data from IRS Publication 6961 from Fall 2018, replacing data from Publication 6187, Fall 2016. Also updating OASI Trust Fund Annual Trustees Report Operations of the OASI Trust Fund, Fiscal Years 2011-15 to be replaced with OASI Trust Fund Annual Trustees Report FY 2013-2027. And lastly CBO Unemployment Compensation Projections from March 2016 iteration to include the April 2018 data. All of this updated the CBO baseline values from the updated 2016-2018 real values into the 2018-2028 projected values.

### CODE REVIEW

**Comment by andersonfrailey** [comment]
Thanks for working on this, @lmm8ka. 

I ran the new files through Tax-Calculator and all of the results seems reasonable. All changes in aggregate tax liability in the PUF are less than 2% and theres only one year in the CPS where the change in tax liability exceeds and absolute value of 2%. Work can be seen [here](http://nbviewer.jupyter.org/github/andersonfrailey/Notebook-Uploads/blob/master/Add2028Projections.ipynb?flush_cache=true).

I couldn't figure out how to change the inputs in the latest version of Tax-Calculator to allow the calculations to go out until 2028, which is why I stopped at 2027. If there's demand for it I'll open a new branch on Tax-Calculator to do that.

cc @martinholmer

**Comment by martinholmer** [comment]
@lmm8ka said in the opening comment to taxdata PR #294:
> updated CBO baseline values

This is a pretty terse explanation of why eight files changed.
At a minimum, you need to explain what the old CBO projection was, what the new CBO project is, and why some values for 2015 and 2016 changed.

**Comment by lmm8ka** [comment]
> @lmm8ka said in the opening comment to taxdata PR #294:
> 
> > updated CBO baseline values
> 
> This is a pretty terse explanation of why eight files changed.
> At a minimum, you need to explain what the old CBO projection was, what the new CBO project is, and why some values for 2015 and 2016 changed.

Just edited the comment to add more info, let me know if you want anything else in that.

**Comment by martinholmer** [comment]
@lmm8ka said:
> Just edited the comment to add more info, let me know if you want anything else in that.

Much more informative.  Thanks.

**Comment by andersonfrailey** [comment]
@martinholmer is there any more analysis of the work done on this branch that you would like to see before being comfortable with merging this PR?

**Comment by martinholmer** [comment]
@andersonfrailey asked in PR #294 :
> is there any more analysis of the work done on this branch that you would like to see before being comfortable with merging this PR?

Go ahead with the merge now.  I won't be able to begin using the new projection until I can also specify the known policy parameter values for 2018 and update all the 2019-2026 parameter values that are rolled back beginning in 2026 under current (TCJA) law.

**Comment by andersonfrailey** [comment]
Actually, upon further review there's a small changes this PR needs. One of the new values for projected returns is incorrect. I will work on getting that done this week.

**Comment by andersonfrailey** [comment]
With the merge of PR #297 this PR is no longer necessary. Closing.

**Pull request closed without merging**
