### PR TITLE
Add nu06 Variable to PUF

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR changes the `nu05` variable to `nu06` in `puf.csv`. As of yet, we can't make this update in the CPS file, but as @MattHJensen pointed out in issue #311, there are users who would like to see this added to the PUF as a first step.

Before merging, I think we should establish what to do with the `nu05` variable in the CPS file. I'm inclined to either a) remove it or b) actually keep it in the PUF so that we will have `nu05` and `nu06`. I'm open to other's suggestions on how to move forward from here.

Also, I found that when I created the new PUF file, the `e19200` variable sum increased by 1. This is probably just rounding error, but I think it's still odd that this has happened.

### CODE REVIEW

**Comment by MattHJensen** [comment]
> Before merging, I think we should establish what to do with the nu05 variable in the CPS file. I'm inclined to either a) remove it or b) actually keep it in the PUF so that we will have nu05 and nu06. I'm open to other's suggestions on how to move forward from here.

I'm inclined to keep both in puf.csv until we add `nu06` to cps.csv, at which time we drop `nu05` from both files, cps.csv and puf.csv. I don't feel strongly about this though if someone else has an alternative preference 

(cc @MaxGhenis).

**Comment by MaxGhenis** [comment]
I'm not aware of major policies using `nu05` so up to you how long to keep it once `nu06` is added (replacing would be OK).

**Comment by MattHJensen** [comment]
@andersonfrailey, are you happy with this approach: 

> I'm inclined to keep both [`nu05` and `nu06`] in puf.csv until we add `nu06` to cps.csv, at which time we drop nu05 from both files, cps.csv and puf.csv.

**Comment by andersonfrailey** [comment]
@MattHJensen Yep this is good with me. I'll update the PR accordingly.

**Comment by andersonfrailey** [comment]
Added nu05 back to the PUF in the latest commit

**Comment by MattHJensen** [comment]
@andersonfrailey, could you please update me on the status of this PR? I apologize if it was ready to be merged before and requires an update now.

**Comment by andersonfrailey** [comment]
@MattHJensen, ready to go! There doesn't seem to be any conflicts. We still can't add `nu06` to the CPS until PR #314 is merged, but I think that one is ready to go as well.

**Comment by andersonfrailey** [comment]
Now that #314 is merged, this will be ready to go when I get the merge conflicts resolved

**Comment by andersonfrailey** [comment]
Fixed up the merge conflicts. Totally removed `nu05`, tests are passing. This is ready to go
@MattHJensen

**Comment by andersonfrailey** [comment]
Doesn't look like there are any more comments so merging

**Pull request merged**
