### PR TITLE
Switch to Tulip Solver

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR is in response to issue #381. It switches us over to the Tulip solver for the stage 2 process. When running the scripts this morning it took about an hour and a half to create weights for both the PUF and CPS, compared to the 24+ hours it took last time I created the weights with our current solver. I'll post results comparisons in a followup comment.

cc @donboyd5

### CODE REVIEW

**Comment by andersonfrailey** [comment]
Relevant changes to the calculations can be found [here](https://github.com/PSLmodels/taxdata/blob/06b169099055f152b8b792661a398706110759c6/history/reports/taxdata_report_2021-06-10.pdf). There are no major changes in output when compared to taxcalc 3.0.0.

**Comment by donboyd5** [comment]
Thanks @andersonfrailey. It looks to me like this is based on the early version of notes I made regarding Tulip. However, if you work through the full post of #381 you will find two major additional improvements:
- scaling of the constraints, which makes the problem more stable numerically and allows it to reach optimality easily
- replace an inefficient approach that was being used in taxdata whereby ~250k constraints were being added unnecessarily, with an approach that achieved the same goal without those unnecessary constraints by instead placing bounds on the variables

If you scroll toward the bottom of #381 you will find a drop-in replacement solver.jl function that implements all of the changes:

1. Tulip instead of Cbc
2. scaling of constraints
3. replace unnecessary constraints with variable bounds

If you use this code (it should be easy to replace what you have now with this) I think you will find that it (a) reaches optimality easily, (b) it is MUCH faster still, and (c) it is more stable numerically.

**Comment by andersonfrailey** [comment]
Last commit makes the changes suggested by @donboyd5

**Comment by andersonfrailey** [comment]
If there are no more comments, I'll merge this at the end of the weekend.

**Comment by MattHJensen** [comment]
Out of curiosity, what was runtime after the latest round of changes?

**Comment by andersonfrailey** [comment]
@MattHJensen running the full make script takes about 30 minutes now!

**Pull request merged**
